### ISSUE TITLE
Missing Moduels in new AzS tools

### ISSUE THREAD

**Issue by mountainbrother** [bottkars/Azurestack-Kickstart#2]
Dear Karsten,

i try to run the ./99 bootstrap.

i get an error that the modules com AzureStack.ComputeAdmin.psm and AzureStack.ServiceAdmin.psm1 could not be loaded. 

A deep dive in the github form AzS tools show me that modules are no longer there.
Whats happend with that ? can you update your cool script. (Double check i had from a older version a copy from both modules after that your script runs without error.)

BR
Günter 

loudadmin              : cloudadmin
AZSTools_Location       : C:\AzureStack-Tools-master
AzureRMProfile          : 2017-03-09-profile
AzureSTackModuleVersion : 1.2.11
SQLRPadmin              : SQLRPadmin
MySQLRPadmin            : MySQLRPadmin
SQLHost                 : SQLHost1
MySQLHost               : MySQLHost1
ISOpath                 : C:\ISO
Updatepath              : C:\Updates
Imagepath               : C:\Image
consumptionSubscription : Default Provider Subscription
meteringSubscription    : Default Provider Subscription

[==>]Setting Endpoints[Done]
[==>]Importing Module C:\AzureStack-Tools-master\Connect\AzureStack.Connect.psm1[Done]
[==>]Importing Module C:\AzureStack-Tools-master\serviceAdmin\AzureStack.ServiceAdmin.psm1Import-Module : Das angegebene Modu
l "C:\AzureStack-Tools-master\serviceAdmin\AzureStack.ServiceAdmin.psm1" wurde nicht 
geladen, da in keinem Modulverzeichnis eine gültige Moduldatei gefunden wurde.
In C:\Users\AzureStackAdmin\Azurestack-Kickstart\admin\99_bootstrap.ps1:231 Zeichen:9
+         Import-Module $Module -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\AzureStack-T...rviceAdmin.psm1:String) [Import-Module], FileNotFound 
   Exception
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
[Done]
[==>]Importing Module C:\AzureStack-Tools-master\ComputeAdmin\AzureStack.ComputeAdmin.psm1Import-Module : Das angegebene Modu
l "C:\AzureStack-Tools-master\ComputeAdmin\AzureStack.ComputeAdmin.psm1" wurde nicht 
geladen, da in keinem Modulverzeichnis eine gültige Moduldatei gefunden wurde.
In C:\Users\AzureStackAdmin\Azurestack-Kickstart\admin\99_bootstrap.ps1:231 Zeichen:9
+         Import-Module $Module -Force
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\AzureStack-T...mputeAdmin.psm1:String) [Import-Module], FileNotFound 
   Exception
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
[Done]
[==>]Registering AzureRM Environment for https://adminmanagement.local.azurestack.external[Done]

**Comment by bottkars** [comment]
yes, they have been removed a week ago. this cause a lot of changes, as also marketplace uploads wont work the way they did before. was kind of a silent "remove". as the removal / new tools usage is slightlöy not ducmented, there i an intermediate solution to use https://github.com/bottkars/azurestack-tools/tree/patch-4
i am currently checking what is affected ( vm and linux marketplace images is the first, plans and quota handling the second one )

i have removed the module load in the latest commit, and had already the Azs.Compute.Admin loaded, wich is the "new" module

**Comment by bottkars** [comment]
made required changes and added a downstrem module for kickstart that contains required commands to create images :-)
